	; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = mpu_6050, gy_521

[env]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.partitions = ota.csv
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
framework = arduino
lib_deps = adafruit/Adafruit MPU6050@^2.2.9
	adafruit/Adafruit Unified Sensor@^1.1.4
	adafruit/Adafruit NeoPixel@^1.15.4
lib_extra_dirs = 
	../shared_libs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
; build_flags = 
; 	-DUSER_SETUP_LOADED
; 	-DUSE_HSPI_PORT
; 	-DTFT_MISO=12
; 	-DTFT_MOSI=13
; 	-DTFT_SCLK=14
; 	-DTFT_CS=15
; 	-DTFT_DC=2
; 	-DTFT_RST=-1
; 	-DTFT_BL=21
; 	-DTFT_BACKLIGHT_ON=HIGH
; 	-DTFT_INVERSION_ON=HIGH
; 	-DSPI_FREQUENCY=55000000
; 	-DSPI_READ_FREQUENCY=20000000
; 	-DSPI_TOUCH_FREQUENCY=2500000
; 	-DLOAD_GLCD
; 	-DLOAD_FONT2
; 	-DLOAD_FONT4
; 	-DLOAD_FONT6
; 	-DLOAD_FONT7
; 	-DLOAD_FONT8
; 	-DLOAD_GFXFF

[env:mpu_6050]
build_flags = 
	${env.build_flags}

[env:gy_521]
build_flags = 
	${env.build_flags}
	-D GY_521
